//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PivecPromotionModel", "FK_Customers_Dealers", "Dealers", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Pivec.Promotion.Data.Dealer), "Customers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Pivec.Promotion.Data.Customer), true)]
[assembly: EdmRelationshipAttribute("PivecPromotionModel", "FK_Customers_Promotions", "Promotions", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Pivec.Promotion.Data.Promotion), "Customers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Pivec.Promotion.Data.Customer), true)]

#endregion

namespace Pivec.Promotion.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PivecPromotionEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PivecPromotionEntities object using the connection string found in the 'PivecPromotionEntities' section of the application configuration file.
        /// </summary>
        public PivecPromotionEntities() : base("name=PivecPromotionEntities", "PivecPromotionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PivecPromotionEntities object.
        /// </summary>
        public PivecPromotionEntities(string connectionString) : base(connectionString, "PivecPromotionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PivecPromotionEntities object.
        /// </summary>
        public PivecPromotionEntities(EntityConnection connection) : base(connection, "PivecPromotionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Dealer> Dealers
        {
            get
            {
                if ((_Dealers == null))
                {
                    _Dealers = base.CreateObjectSet<Dealer>("Dealers");
                }
                return _Dealers;
            }
        }
        private ObjectSet<Dealer> _Dealers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Promotion> Promotions
        {
            get
            {
                if ((_Promotions == null))
                {
                    _Promotions = base.CreateObjectSet<Promotion>("Promotions");
                }
                return _Promotions;
            }
        }
        private ObjectSet<Promotion> _Promotions;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Dealers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDealers(Dealer dealer)
        {
            base.AddObject("Dealers", dealer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Promotions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPromotions(Promotion promotion)
        {
            base.AddObject("Promotions", promotion);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PivecPromotionModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="promotionId">Initial value of the PromotionId property.</param>
        /// <param name="dealerId">Initial value of the DealerId property.</param>
        /// <param name="salespersonCode">Initial value of the SalespersonCode property.</param>
        /// <param name="driverLicenseNumber">Initial value of the DriverLicenseNumber property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        public static Customer CreateCustomer(global::System.Guid id, global::System.Guid promotionId, global::System.Guid dealerId, global::System.String salespersonCode, global::System.String driverLicenseNumber, global::System.String firstName, global::System.String lastName, global::System.String address, global::System.String email, global::System.DateTime dateCreated)
        {
            Customer customer = new Customer();
            customer.Id = id;
            customer.PromotionId = promotionId;
            customer.DealerId = dealerId;
            customer.SalespersonCode = salespersonCode;
            customer.DriverLicenseNumber = driverLicenseNumber;
            customer.FirstName = firstName;
            customer.LastName = lastName;
            customer.Address = address;
            customer.Email = email;
            customer.DateCreated = dateCreated;
            return customer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PromotionId
        {
            get
            {
                return _PromotionId;
            }
            set
            {
                OnPromotionIdChanging(value);
                ReportPropertyChanging("PromotionId");
                _PromotionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PromotionId");
                OnPromotionIdChanged();
            }
        }
        private global::System.Guid _PromotionId;
        partial void OnPromotionIdChanging(global::System.Guid value);
        partial void OnPromotionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid DealerId
        {
            get
            {
                return _DealerId;
            }
            set
            {
                OnDealerIdChanging(value);
                ReportPropertyChanging("DealerId");
                _DealerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DealerId");
                OnDealerIdChanged();
            }
        }
        private global::System.Guid _DealerId;
        partial void OnDealerIdChanging(global::System.Guid value);
        partial void OnDealerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SalespersonCode
        {
            get
            {
                return _SalespersonCode;
            }
            set
            {
                OnSalespersonCodeChanging(value);
                ReportPropertyChanging("SalespersonCode");
                _SalespersonCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SalespersonCode");
                OnSalespersonCodeChanged();
            }
        }
        private global::System.String _SalespersonCode;
        partial void OnSalespersonCodeChanging(global::System.String value);
        partial void OnSalespersonCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DriverLicenseNumber
        {
            get
            {
                return _DriverLicenseNumber;
            }
            set
            {
                OnDriverLicenseNumberChanging(value);
                ReportPropertyChanging("DriverLicenseNumber");
                _DriverLicenseNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DriverLicenseNumber");
                OnDriverLicenseNumberChanged();
            }
        }
        private global::System.String _DriverLicenseNumber;
        partial void OnDriverLicenseNumberChanging(global::System.String value);
        partial void OnDriverLicenseNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PivecPromotionModel", "FK_Customers_Dealers", "Dealers")]
        public Dealer Dealer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dealer>("PivecPromotionModel.FK_Customers_Dealers", "Dealers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dealer>("PivecPromotionModel.FK_Customers_Dealers", "Dealers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Dealer> DealerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dealer>("PivecPromotionModel.FK_Customers_Dealers", "Dealers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Dealer>("PivecPromotionModel.FK_Customers_Dealers", "Dealers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PivecPromotionModel", "FK_Customers_Promotions", "Promotions")]
        public Promotion Promotion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Promotion>("PivecPromotionModel.FK_Customers_Promotions", "Promotions").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Promotion>("PivecPromotionModel.FK_Customers_Promotions", "Promotions").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Promotion> PromotionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Promotion>("PivecPromotionModel.FK_Customers_Promotions", "Promotions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Promotion>("PivecPromotionModel.FK_Customers_Promotions", "Promotions", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PivecPromotionModel", Name="Dealer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dealer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Dealer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Dealer CreateDealer(global::System.Guid id, global::System.String name)
        {
            Dealer dealer = new Dealer();
            dealer.Id = id;
            dealer.Name = name;
            return dealer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PivecPromotionModel", "FK_Customers_Dealers", "Customers")]
        public EntityCollection<Customer> Customers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Customer>("PivecPromotionModel.FK_Customers_Dealers", "Customers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Customer>("PivecPromotionModel.FK_Customers_Dealers", "Customers", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PivecPromotionModel", Name="Promotion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Promotion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Promotion object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static Promotion CreatePromotion(global::System.Guid id, global::System.String name, global::System.Boolean isActive)
        {
            Promotion promotion = new Promotion();
            promotion.Id = id;
            promotion.Name = name;
            promotion.IsActive = isActive;
            return promotion;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PivecPromotionModel", "FK_Customers_Promotions", "Customers")]
        public EntityCollection<Customer> Customers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Customer>("PivecPromotionModel.FK_Customers_Promotions", "Customers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Customer>("PivecPromotionModel.FK_Customers_Promotions", "Customers", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
